### ISSUE TITLE
Cannot install polymer

### ISSUE THREAD

**Issue by ojss** [alchapone/polymer-rails#73]
I followed the steps and I did install the latest version the polymer-rails gem but the install command is throwing a bunch of errors.
command:
```
gem install polymer-rails
```

The gem still have problems with the latest version of sprockets? 
Howw do I solve this problem?

**Comment by LuisHCK** [comment]
I'm trying to migrate my simple app to Polymer but i having the same problem. Any idea?
```
luishck@HP-14:~/projects/liveapp$ rails g polymer:install
/home/luishck/.rvm/gems/ruby-2.2.4/gems/polymer-rails-1.1.0/lib/polymer-rails/railtie.rb:7:in `block in <class:Railtie>': undefined method `context_class' for nil:NilClass (NoMethodError)
	from /home/luishck/.rvm/gems/ruby-2.2.4@global/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/luishck/.rvm/gems/ruby-2.2.4@global/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /home/luishck/.rvm/gems/ruby-2.2.4@global/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/luishck/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/luishck/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/luishck/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/luishck/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/luishck/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/luishck/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/luishck/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/luishck/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/luishck/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/luishck/.rvm/gems/ruby-2.2.4@global/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/luishck/.rvm/gems/ruby-2.2.4@global/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
	from /home/luishck/projects/liveapp/config/environment.rb:5:in `<top (required)>'
	from /home/luishck/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/luishck/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/luishck/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/luishck/.rvm/gems/ruby-2.2.4@global/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /home/luishck/.rvm/gems/ruby-2.2.4/gems/spring-1.6.2/lib/spring/application.rb:92:in `preload'
	from /home/luishck/.rvm/gems/ruby-2.2.4/gems/spring-1.6.2/lib/spring/application.rb:143:in `serve'
	from /home/luishck/.rvm/gems/ruby-2.2.4/gems/spring-1.6.2/lib/spring/application.rb:131:in `block in run'
	from /home/luishck/.rvm/gems/ruby-2.2.4/gems/spring-1.6.2/lib/spring/application.rb:125:in `loop'
	from /home/luishck/.rvm/gems/ruby-2.2.4/gems/spring-1.6.2/lib/spring/application.rb:125:in `run'
	from /home/luishck/.rvm/gems/ruby-2.2.4/gems/spring-1.6.2/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/luishck/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/luishck/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

```

**Comment by ojss** [comment]
@LuisHCK I have a similar problem but it involves the sprocket gem..

**Comment by LuisHCK** [comment]
@ojss yes, Sprocket seems to be the problem. Well! Wait help! :yum:

**Comment by taniarv** [comment]
I just updated to rails 4.2.5.1 and sprockets-rails 3.0.0 and same problem. I have downgraded to sprockets-rails 2.3.3 and it works again...

**Comment by ojss** [comment]
@taniarv Looks like I will have to downgrade sprockets too. Any side effects of the downgrade?

@alchapone is there anything that can be done to make this gem sprockets 3.x.x compatible?

**Comment by taniarv** [comment]
@ojss no, everything is running fine after downgrading :)

**Comment by ojss** [comment]
Okay, I downgraded to sprockets 2.12.4 and was able to install polymer.

Does it matter if I use sprockets or sprockets-rails(I believe is a wrapper around the normal sprockets)?

Ojas Shirekar

**Comment by alchapone** [comment]
@ojss Try using latest version of `polymer-rails`. It should now support sprockets v3.x

**Comment by ojss** [comment]
I will be sure to try it once I get some free time on my hands :)
Ojas Shirekar
